name: C build code

on:
    workflow_dispatch:
    
    push:
        branches:
          - 'main'
          - '**'   #all banches name
        path-ignore: #don't run workflow if changes to files
            - 'release_notes'
            - '.gitignore'
            - 'README.md'

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
          - name: checkout code
            uses: actions/checkout@v4
            
          - name: clean previous build directories
            run: make clean || echo "no build directory to clean"
            
          - name: setup enviroment
            run: | 
               mkdir -p build bin logs
               echo "TIMESTAMP=$(date +'%Y%m%d')" >> $GITHUB_ENV
            
          - name: build with make
            run: | 
                echo "----- build start $(date +'%d-%m-%Y %H:%M:%S') -----" | tee logs/build_output_£{{ env.TIMESTAMP }}.log 
                make 2>&1 | tee -a logs/build_output_£{{ env.TIMESTAMP }}.log
                echo -e "----- build end $(date +'%d-%m-%Y %H:%M:%S') -----\n" | tee -a logs/build_output_£{{ env.TIMESTAMP }}.log
            
          - name: upload logs
            uses: actions/upload-artifact@v4
            with:
                name: build-logs
                path: logs/build_output_£{{ env.TIMESTAMP }}.log
            
          - name: Check if binary exists
            run: |
                if [ ! -f bin/my_program ]; then
                    echo "Binary not found. check for build fail."
                    exit 1
                fi

          - name: Upload binary
            uses: actions/upload-artifact@v4
            with:
                name: binary
                path: bin/my_program    