
name: C build code

on:
    workflow_dispatch:
    
    push:
        branches:
          - 'main'
          - '**'   #all banches name
        path-ignore:
            -'!release_notes'

    
 jobs:
    build:
        run-on: ubuntu-latest
    